algorithm_type:
  Algorithm:
    algorithm: RDUCB
    algorithm_random_seed: 1
    eps: -1
    exploration_weight: 'lambda t: 0.5 * np.log(2*t)'
    graphSamplingNumIter: 100
    initial_kernel_params:
      lengthscale: 0.1
      variance: 0.5
    learnDependencyStructureRate: 1
    lengthscaleNumIter: 2
    max_eval: -4
    noise_var: 0.1
    param_n_iter: 16
    size_of_random_graph: 0.2
data_type:
  Simple:
    data_random_seed: 1
    fn_noise_var: 0.15
    grid_size: 150
    dimension: 250
    simple_fn: Stybtang
n_iter: 500
n_rand: 10
