algorithm_type:
  Algorithm:
    algorithm: RDUCB
    algorithm_random_seed: 1
    eps: -1
    exploration_weight: 'lambda t: 0.5 * np.log(2*t)'
    graphSamplingNumIter: 100
    initial_kernel_params:
      lengthscale: 0.1
      variance: 0.5
    learnDependencyStructureRate: 1
    lengthscaleNumIter: 2
    max_eval: -4
    noise_var: 0.1
    param_n_iter: 16
    size_of_random_graph: 0.2
data_type:
  NAS:
    bench_type: FcnetLoader
    data_random_seed: 3
    fcnet_filename: slice_localization
    # input the home directory of the NAS data if it is not at root
    #home_dir:
n_iter: 200
n_rand: 10
