verbose: false
compute_ppl: true
return_block_size: true
logging: true
em_splitter: surprisal

max_len: 2147483647
chunk_size: 512
conv_type: phi-3-mini-inst

extended_passkey: 1024

model:
  type: em-llm
  path: microsoft/Phi-3.5-mini-instruct
  min_block_size: 8
  max_block_size: 64
  n_init: 128
  n_local: 1024
  n_mem: 3072
  repr_topk: 4
  max_cached_block: 384  # must be greater than n_mem/min_block_size
  exc_block_size: 512
  base: 10000
  distance_scale: 1.0
  surprisal_threshold_gamma: 1.0
  attn_implementation: eager  

  min_free_cpu_memory: 100
  disk_offload_threshold: 300000
  vector_offload_threshold: 50000

  similarity_refinement_kwargs:
    similarity_refinement: false
    refine_with_buffer: true
    refine_from_layer: 20
    similarity_metric: modularity

  contiguity_buffer_kwargs:
    use_contiguity_buffer: false
    contiguity_buffer_size: 0.3
  
  uniform_blocks: false
  random_topk_blocks: false