name: "eagle"

model_class:
  _target_: hydra.utils.get_object
  path: moa_spec.models.train.eagle.EAGLELlamaForCausalLM

model_config:
  training_noise: True
  noise_uniform_scale: 0.2
  default_layer: True  # ignore the 3 next options if True

  # set default_layer to False and use those options to play with the size and the number of layers of the drafter
  number_of_layers: null
  drafter_num_key_value_heads: null
  drafter_intermediate_size: null
