# @package _global_
defaults:
  - override /hydra: parallel
  - _self_

hydra:
  launcher:
    n_jobs: 100
  mode: MULTIRUN
  sweeper:
    params:
      task: gsm8k,humaneval
      method: fs,fs-cot,zs-cot,direct
      llm@agent.llm: fschat/mixstral,fschat/openchat_3.5,fschat/deepseek-6.7b
      +agent.llm.temperature: 0.5
      +seed: 0,1
