# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
  - override launcher: joblib

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/runs/exp_${hydra:job.override_dirname}/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${paths.log_dir}/multiruns/${experiment_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}_${hydra:job.override_dirname}

launcher:
  n_jobs: 10

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
