# Model arguments
model_name_or_path: sft-model-path
torch_dtype: null

# Data training arguments
dataset_mixer:
  Anthropic/hh-rlhf: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# DPOTrainer arguments
fp16: true
beta: 0.1
do_train: true
do_eval: true
eval_strategy: epoch
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1024
num_train_epochs: 3
optim: adamw_torch
output_dir: tmp
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: epoch
save_total_limit: 3
seed: 42
warmup_ratio: 0.1
report_to:
- tensorboard
remove_unused_columns: false
logging_first_step: true