# @package _global_
agent:
  pre_action_flow:
    _target_: agent.commands.DecisionFlow
    choices:
      - _target_: agent.commands.SequentialFlow
        name: react
        description: Think and then act
        sequence:
          - _target_: agent.commands.Think
          - _target_: agent.commands.Act
      - _target_: agent.commands.Act
  prompt_builder:
    default_kwargs:
      cot_type: react
