# @package _global_
agent:
  pre_action_flow:
    _target_: agent.commands.SequentialFlow
    name: retrieve and answer
    description: Search Database and answer to a question
    sequence:
      - _target_: agent.commands.VectorDB
        path_to_database: /nfs/aiml/shino/
        database_name: database_all
        # path_to_docs: /nfs/aiml/shino/hotpot_db_1
        # path_to_save_db: /nfs/aiml/shino/

        top_k: 2
      - _target_: agent.commands.Act

  prompt_builder:
    default_kwargs:
      cot_type: few_shot
