# @package _global_
agent:
  pre_action_flow:
    _target_: agent.commands.SequentialFlow
    sequence:
      - _target_: agent.commands.Act
  prompt_builder:
    default_kwargs:
      cot_type: zero_shot_cot
