# @package _global_
agent:
  pre_action_flow: ???
  prompt_builder:
    template_paths:
      - hyperopt
#      - default

task:
  _target_: agent.tasks.hyperopt.HyperOpt

  workspace_path: ./workspace/hyperopt

  name: hyperopt
  description:
  subtask: null
  version: v0.1

max_episodes: 1
max_env_steps: 1