# Script generated by DRiLLS agent

read asap7.lib
read adder.v

strash
refactor
rewrite -z
rewrite -z
rewrite -z
resub -z
refactor
refactor
rewrite -z
refactor
rewrite
rewrite
resub
rewrite
rewrite
resub
balance
resub
refactor -z
balance
rewrite
rewrite -z
balance
resub -z
rewrite -z
refactor
rewrite -z
refactor -z

write_verilog adder_synth_drills.v

map -D 2000
stime