# Script generated by DRiLLS agent

read asap7.lib
read bar.v

strash
rewrite -z
balance
rewrite -z
refactor
refactor -z
refactor
resub
refactor -z
refactor
rewrite
refactor -z
rewrite -z
resub
refactor -z
rewrite -z
refactor
balance
resub -z
rewrite
rewrite -z
rewrite
rewrite
rewrite -z
resub
resub
balance
rewrite
resub -z
balance
rewrite -z
rewrite -z
resub -z
rewrite
rewrite
refactor
refactor
refactor
balance
resub -z
rewrite -z
resub -z
resub -z
balance
refactor -z
refactor -z
rewrite -z

write_verilog bar_synth_drills.v

map -D 800
stime
