# Script generated by DRiLLS agent

read asap7.lib
read div.v

strash
rewrite
refactor -z
refactor -z
refactor -z
resub
rewrite -z
resub -z
refactor -z
rewrite
resub -z
rewrite -z
rewrite
rewrite -z
resub
refactor
resub
refactor -z
refactor -z
refactor -z
refactor
refactor
rewrite
resub -z
refactor -z
resub
refactor -z
resub -z
resub -z
refactor -z
resub
refactor -z
resub -z
refactor
resub -z
resub -z
resub
refactor -z
rewrite
refactor -z
rewrite
rewrite
rewrite -z
resub
refactor
rewrite -z
refactor -z
refactor
refactor
resub

write_verilog div_synth_drills.v

map -D 75000
stime
