# Script generated by DRiLLS agent

read asap7.lib
read hyp.v

strash
rewrite
resub
resub
resub
resub
resub
resub
balance
balance
rewrite -z
resub
resub
resub
refactor -z
resub
resub
resub
resub
resub
refactor -z
resub
resub -z
resub
resub
resub -z
resub
resub
resub
resub
balance
balance
resub
resub -z
resub
rewrite -z

write_verilog hyp_synth_drills.v

map -D 1000000
stime
