# Script generated by DRiLLS agent

read asap7.lib
read log2.v

strash
resub -z
refactor -z
refactor -z
refactor
resub
refactor
refactor -z
refactor -z
refactor
resub -z
resub -z
refactor -z
refactor -z
resub -z
refactor
refactor -z
resub -z
refactor
resub
refactor
resub -z
resub -z
balance

write_verilog log2_synth_drills.v

map -D 7500
stime
