# Script generated by DRiLLS agent

read asap7.lib
read sqrt.v

strash
refactor -z
resub -z
refactor -z
refactor -z
refactor -z
refactor
balance
rewrite -z
rewrite -z
resub
refactor -z
refactor -z
refactor -z
balance
resub -z
resub -z
resub -z
refactor -z
rewrite -z

write_verilog sqrt_synth_drills.v

map -D 170000
stime
